name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools-scm
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Extract version from release tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        # Keep the version as-is (no v prefix removal needed)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
        echo "Git tag should be available for setuptools-scm"
    
    - name: Verify git tag and setuptools-scm
      run: |
        echo "Available git tags:"
        git tag --list | tail -10
        echo "Current commit: $(git rev-parse HEAD)"
        echo "Current branch/ref: $GITHUB_REF"
        
        # Check if we're on a tagged commit
        CURRENT_TAG=$(git describe --exact-match --tags HEAD 2>/dev/null || echo "")
        if [ -z "$CURRENT_TAG" ]; then
            echo "❌ ERROR: Current commit is not tagged!"
            echo "setuptools-scm requires the exact commit to be tagged."
            echo "This will result in a development version that PyPI will reject."
            exit 1
        else
            echo "✅ Current commit has tag: $CURRENT_TAG"
        fi
        
        # Install setuptools-scm first
        python -m pip install --upgrade pip setuptools-scm
        
        # Check what version setuptools-scm will generate
        echo "setuptools-scm version preview:"
        if ! VERSION_OUTPUT=$(python -c "import setuptools_scm; version = setuptools_scm.get_version(); print(version)" 2>&1); then
            echo "❌ ERROR: Failed to get version from setuptools-scm"
            echo "Output: $VERSION_OUTPUT"
            exit 1
        fi
        
        echo "Generated version: $VERSION_OUTPUT"
        
        # Check if it contains development markers (more strict check)
        echo "Checking version for development markers..."
        if [[ "$VERSION_OUTPUT" =~ dev ]] || [[ "$VERSION_OUTPUT" =~ \+g ]] || [[ "$VERSION_OUTPUT" =~ \.d[0-9] ]]; then
            echo "❌ ERROR: Development version detected: $VERSION_OUTPUT"
            echo "This will be rejected by PyPI. The commit must be exactly on a tagged commit."
            echo "Current tags near HEAD:"
            git tag --sort=-version:refname | head -5
            echo "Expected a clean version like: 1.0.9"
            echo ""
            echo "DEBUGGING INFO:"
            echo "Current commit: $(git rev-parse HEAD)"
            CURRENT_TAG="${GITHUB_REF#refs/tags/}"
            echo "Expected tag: $CURRENT_TAG"
            echo "Tag commit: $(git rev-list -n 1 $CURRENT_TAG 2>/dev/null || echo 'Tag not found')"
            echo "Commits since tag: $(git rev-list --count HEAD ^$CURRENT_TAG 2>/dev/null || echo 'Cannot calculate')"
            echo ""
            echo "WORKFLOW WILL EXIT NOW TO PREVENT PYPI ERROR"
            exit 1
        fi
        
        echo "✅ SUCCESS: Clean release version detected: $VERSION_OUTPUT"
        
        # Double-check: ensure version matches expected tag
        EXPECTED_VERSION="${GITHUB_REF#refs/tags/}"
        if [[ "$VERSION_OUTPUT" != "$EXPECTED_VERSION" ]]; then
            echo "❌ ERROR: Version mismatch!"
            echo "Expected: $EXPECTED_VERSION"
            echo "Generated: $VERSION_OUTPUT" 
            echo "WORKFLOW WILL EXIT NOW TO PREVENT PYPI ERROR"
            exit 1
        fi
        
        echo "✅ SUCCESS: Version matches expected tag: $VERSION_OUTPUT"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine setuptools-scm
    
    - name: Build package
      run: |
        echo "Building package..."
        python -m build
        echo "Build completed. Checking output:"
        ls -la dist/
        
        # Verify the built package has the expected version
        WHEEL_FILE=$(ls dist/*.whl | head -1)
        if [ -f "$WHEEL_FILE" ]; then
            echo "✅ Wheel file created: $(basename $WHEEL_FILE)"
        else
            echo "❌ ERROR: No wheel file found"
            exit 1
        fi
    
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verify-metadata: false
        skip-existing: true